### ISSUE TITLE
Request: Support for v0.7.0

### ISSUE THREAD

**Issue by kiok46** [nathanielCherian/vscode-cashscript#5]
Hi!
Absolutely love this extension!
I was wondering if there is a plan to support 0.7.0 of cashscript.

Thanks!

**Comment by nathanielCherian** [comment]
Thank you, I really appreciate that! 

Yes, I've made changes that reflects cashscript ```v0.7.0-next``` (mainly the new [introspection syntax](https://github.com/Bitcoin-com/cashscript/issues/92#issuecomment-944211071)) in a [new branch](https://github.com/nathanielCherian/vscode-cashscript/tree/next).

There are a few more minor features I need to add for ```v0.7.0``` but I will get those done soon!

**Comment by kiok46** [comment]
Awesome! Thanks again.

**Comment by nathanielCherian** [comment]
Just published v0.2.0!
