### ISSUE TITLE
Support for CashScript v0.8.0

### ISSUE THREAD

**Issue by rkalis** [nathanielCherian/vscode-cashscript#7]
Hello hello! How have you been?

BCH is upgrading to add new functionality the 15th of May. We've updated `cashscript@next` (`v0.8.0-next.3`) to add support for those new features. The new features can be found at https://next.cashscript.org/docs/releases/release-notes#v080.

New syntax:
```
tx.inputs[i].tokenCategory
tx.inputs[i].nftCommitment
tx.inputs[i].tokenAmount

tx.outputs[i].tokenCategory
tx.outputs[i].nftCommitment
tx.outputs[i].tokenAmount

new LockingBytecodeP2SH20(...)
new LockingBytecodeP2SH32(...)
```

removed syntax:
```
new LockingBytecodeP2SH(...)
```

If you're able to add support for these new features that would be awesome. We're planning to release the production version of v0.8.0 shortly after May 15th. If you don't have the time to update the vscode library, @mr-zwets or I can probably try to raise a PR instead. Let me know what you prefer.

**Comment by khirvy019** [comment]
Looking forward to this update 🙇

**Comment by rkalis** [comment]
Just opened a PR for this: #8
